/**
 * Adar JS Integration Example
 * This script shows how to use scoped class names from adar-modules.json
 */

async function init() {
    try {
        // 1. Fetch the mapping generated by adarpc build
        const response = await fetch('./adar-modules.json');
        if (!response.ok) return;
        
        const styles = await response.json();
        console.log('Adar Scoped Classes:', styles);

        // 2. Example: Apply a scoped class to an element dynamically
        // We look for 'btn-primary' defined in 'style.adar'
        const styleMapping = styles['style.adar'];
        if (styleMapping && styleMapping['btn-primary']) {
            const scopedClass = styleMapping['btn-primary'];
            const btn = document.getElementById('btn-start');
            
            if (btn) {
                console.log(`Applying scoped class: ${scopedClass}`);
                // The class is already there if used in HTML, 
                // but this shows how to get it for JS-created elements.
            }
        }
    } catch (err) {
        console.info('adar-modules.json not found yet. Run "adarpc build" with scope = true.');
    }
}

init();
